format = "$all$fill$cmd_duration$time$battery$line_break$jobs$status$container$shell$character"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[](green)"

[cmd_duration]
style = "yellow"
format = "[$duration ❮ ]($style)"

[directory]
style = "cyan"
read_only = " 󰌾"
truncation_length = 8
truncation_symbol = "…/"

[fill]
symbol = " "

[jobs]
symbol = ""
style = "blue"

[time]
disabled = false
style = "white dimmed"
format = "[$time]($style) "

[[battery.display]]
style = "bold red"
threshold = 10

[[battery.display]]
style = "bold yellow"
threshold = 30

[[battery.display]]
style = "purple"
threshold = 100

[custom.git_simple]
command = "git-simple"
require_repo = true
when = true
ignore_timeout = true
style = ""
disabled = true

[aws]
# symbol = "  "
symbol = "  "

[bun]
symbol = " "
format = '[$symbol($version)]($style) '

[c]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = "  "

[git_branch]
symbol = " "

[hg_branch]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[nim]
symbol = "󰆥 "

[nodejs]
symbol = " "
detect_files = [
  "package.json",
  ".node-version",
  ".nvmrc",
  "!bunfig.toml",
  "!bun.lockb",
  "!bun.lock",
]

[os.symbols]
Macos = " "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version}) (\($virtualenv\))]($style)'
python_binary = [
  "./venv/bin/python",
  "./bin/python",
  "python",
  "python3",
  "python2",
]

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = " "
disabled = true

[zig]
symbol = " "
