[[mgr.prepend_keymap]]
on = ["m", "z"]
run = "linemode size_and_mtime"
desc = "Set linemode to size and mtime"

[[mgr.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch zip"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on = "Q"
run = "quit"
desc = "Exit the process"

[[mgr.prepend_keymap]]
on = "q"
run = "quit --no-cwd-file"
desc = "Exit the process without writing cwd-file"

[[mgr.prepend_keymap]]
on = ["?"]
run = "help"
desc = "Open help"

[[input.prepend_keymap]]
on = ["?"]
run = "help"
desc = "Open help"
