[mgr]
ratio = [1, 3, 4]
sort_by = "natural"
sort_dir_first = false
linemode = "size_and_mtime"

[preview]
wrap = "yes"

[opener]
extract = [
  { run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[plugin]
prepend_previewers = [
  { mime = "application/xz", run = "ouch" },
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/zstd", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-tar", run = "ouch" },
  { mime = "application/x-zstd", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/vnd.rar", run = "ouch" },
  { mime = "application/java-archive", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
]
